apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: real-estate-for-all
  template:
    metadata:
      labels:
        app: real-estate-for-all
    spec:
      containers:
        - name: real-estate-for-all
          image: 1645370/real-estate-for-all:$(Build.BuildId)
          ports:
            - containerPort: 3000